# FIAT
AED-USD: 'currencylayer.com'
AFN-USD: 'currencylayer.com'
ALL-USD: 'currencylayer.com'
AMD-USD: 'currencylayer.com'
ANG-USD: 'currencylayer.com'
AOA-USD: 'currencylayer.com'
ARS-USD: 'currencylayer.com'
AUD-USD: 'currencylayer.com'
AWG-USD: 'currencylayer.com'
AZN-USD: 'currencylayer.com'
BAM-USD: 'currencylayer.com'
BBD-USD: 'currencylayer.com'
BDT-USD: 'currencylayer.com'
BGN-USD: 'currencylayer.com'
BHD-USD: 'currencylayer.com'
BIF-USD: 'currencylayer.com'
BMD-USD: 'currencylayer.com'
BND-USD: 'currencylayer.com'
BOB-USD: 'currencylayer.com'
BRL-USD: 'currencylayer.com'
BSD-USD: 'currencylayer.com'
BTN-USD: 'currencylayer.com'
BWP-USD: 'currencylayer.com'
BYR-USD: 'currencylayer.com'
BZD-USD: 'currencylayer.com'
CAD-USD: 'currencylayer.com'
CDF-USD: 'currencylayer.com'
CHF-USD: 'currencylayer.com'
CLF-USD: 'currencylayer.com'
CLP-USD: 'currencylayer.com'
CNY-USD: 'currencylayer.com'
COP-USD: 'currencylayer.com'
CRC-USD: 'currencylayer.com'
CUC-USD: 'currencylayer.com'
CUP-USD: 'currencylayer.com'
CVE-USD: 'currencylayer.com'
CZK-USD: 'currencylayer.com'
DJF-USD: 'currencylayer.com'
DKK-USD: 'currencylayer.com'
DOP-USD: 'currencylayer.com'
DZD-USD: 'currencylayer.com'
EGP-USD: 'currencylayer.com'
ERN-USD: 'currencylayer.com'
ETB-USD: 'currencylayer.com'
EUR-USD: 'currencylayer.com'
FJD-USD: 'currencylayer.com'
FKP-USD: 'currencylayer.com'
GBP-USD: 'currencylayer.com'
GEL-USD: 'currencylayer.com'
GGP-USD: 'currencylayer.com'
GHS-USD: 'currencylayer.com'
GIP-USD: 'currencylayer.com'
GMD-USD: 'currencylayer.com'
GNF-USD: 'currencylayer.com'
GTQ-USD: 'currencylayer.com'
GYD-USD: 'currencylayer.com'
HKD-USD: 'currencylayer.com'
HNL-USD: 'currencylayer.com'
HRK-USD: 'currencylayer.com'
HTG-USD: 'currencylayer.com'
HUF-USD: 'currencylayer.com'
IDR-USD: 'currencylayer.com'
ILS-USD: 'currencylayer.com'
IMP-USD: 'currencylayer.com'
INR-USD: 'currencylayer.com'
IQD-USD: 'currencylayer.com'
IRR-USD: 'currencylayer.com'
ISK-USD: 'currencylayer.com'
JEP-USD: 'currencylayer.com'
JMD-USD: 'currencylayer.com'
JOD-USD: 'currencylayer.com'
JPY-USD: 'currencylayer.com'
KES-USD: 'currencylayer.com'
KGS-USD: 'currencylayer.com'
KHR-USD: 'currencylayer.com'
KMF-USD: 'currencylayer.com'
KPW-USD: 'currencylayer.com'
KRW-USD: 'currencylayer.com'
KWD-USD: 'currencylayer.com'
KYD-USD: 'currencylayer.com'
KZT-USD: 'currencylayer.com'
LAK-USD: 'currencylayer.com'
LBP-USD: 'currencylayer.com'
LKR-USD: 'currencylayer.com'
LRD-USD: 'currencylayer.com'
LSL-USD: 'currencylayer.com'
LTL-USD: 'currencylayer.com'
LVL-USD: 'currencylayer.com'
LYD-USD: 'currencylayer.com'
MAD-USD: 'currencylayer.com'
MDL-USD: 'currencylayer.com'
MGA-USD: 'currencylayer.com'
MKD-USD: 'currencylayer.com'
MMK-USD: 'currencylayer.com'
MNT-USD: 'currencylayer.com'
MOP-USD: 'currencylayer.com'
MRO-USD: 'currencylayer.com'
MUR-USD: 'currencylayer.com'
MVR-USD: 'currencylayer.com'
MWK-USD: 'currencylayer.com'
MXN-USD: 'currencylayer.com'
MYR-USD: 'currencylayer.com'
MZN-USD: 'currencylayer.com'
NAD-USD: 'currencylayer.com'
NGN-USD: 'currencylayer.com'
NIO-USD: 'currencylayer.com'
NOK-USD: 'currencylayer.com'
NPR-USD: 'currencylayer.com'
NZD-USD: 'currencylayer.com'
OMR-USD: 'currencylayer.com'
PAB-USD: 'currencylayer.com'
PEN-USD: 'currencylayer.com'
PGK-USD: 'currencylayer.com'
PHP-USD: 'currencylayer.com'
PKR-USD: 'currencylayer.com'
PLN-USD: 'currencylayer.com'
PYG-USD: 'currencylayer.com'
QAR-USD: 'currencylayer.com'
RON-USD: 'currencylayer.com'
RSD-USD: 'currencylayer.com'
RUB-USD: 'currencylayer.com'
RWF-USD: 'currencylayer.com'
SAR-USD: 'currencylayer.com'
SBD-USD: 'currencylayer.com'
SCR-USD: 'currencylayer.com'
SDG-USD: 'currencylayer.com'
SEK-USD: 'currencylayer.com'
SGD-USD: 'currencylayer.com'
SHP-USD: 'currencylayer.com'
SLL-USD: 'currencylayer.com'
SOS-USD: 'currencylayer.com'
SRD-USD: 'currencylayer.com'
STD-USD: 'currencylayer.com'
SVC-USD: 'currencylayer.com'
SYP-USD: 'currencylayer.com'
SZL-USD: 'currencylayer.com'
THB-USD: 'currencylayer.com'
TJS-USD: 'currencylayer.com'
TMT-USD: 'currencylayer.com'
TND-USD: 'currencylayer.com'
TOP-USD: 'currencylayer.com'
TRY-USD: 'currencylayer.com'
TTD-USD: 'currencylayer.com'
TWD-USD: 'currencylayer.com'
TZS-USD: 'currencylayer.com'
UAH-USD: 'currencylayer.com'
UGX-USD: 'currencylayer.com'
UYU-USD: 'currencylayer.com'
UZS-USD: 'currencylayer.com'
VEF-USD: 'currencylayer.com'
VND-USD: 'currencylayer.com'
VUV-USD: 'currencylayer.com'
WST-USD: 'currencylayer.com'
XAF-USD: 'currencylayer.com'
XAG-USD: 'currencylayer.com'
XAU-USD: 'currencylayer.com'
XCD-USD: 'currencylayer.com'
XDR-USD: 'currencylayer.com'
XOF-USD: 'currencylayer.com'
XPF-USD: 'currencylayer.com'
YER-USD: 'currencylayer.com'
ZAR-USD: 'currencylayer.com'
ZMK-USD: 'currencylayer.com'
ZMW-USD: 'currencylayer.com'
ZWL-USD: 'currencylayer.com'
