# CRYPTO
# BCH
BCH-BTC: bitcoinaverage.com
BCH-CLP: bitcoinaverage.com
BCH-EUR: bitcoinaverage.com
BCH-GBP: bitcoinaverage.com
BCH-JPY: bitcoinaverage.com
BCH-USD: bitcoinaverage.com
# BTC
BTC-ARS: bitcoinaverage.com
BTC-CLP: bitcoinaverage.com
BTC-EUR: bitcoinaverage.com
BTC-GBP: bitcoinaverage.com
BTC-JPY: bitcoinaverage.com
BTC-USD: bitcoinaverage.com
# ETH
ETH-BTC: bitcoinaverage.com
ETH-CLP: bitcoinaverage.com
ETH-EUR: bitcoinaverage.com
ETH-GBP: bitcoinaverage.com
ETH-JPY: bitcoinaverage.com
ETH-USD: bitcoinaverage.com
# LTC
LTC-BTC: bitcoinaverage.com
LTC-CLP: bitcoinaverage.com
LTC-EUR: bitcoinaverage.com
LTC-GBP: bitcoinaverage.com
LTC-JPY: bitcoinaverage.com
LTC-USD: bitcoinaverage.com
# XLM
XLM-BTC: bitcoinaverage.com

# FIAT
# USD
USD-ARS: currencylayer.com
USD-BRL: currencylayer.com
USD-CLP: currencylayer.com
USD-COP: currencylayer.com
USD-EUR: currencylayer.com
USD-GBP: currencylayer.com
USD-JPY: currencylayer.com
USD-PEN: currencylayer.com
# CLP
CLP-ARS: currencylayer.com
CLP-BRL: currencylayer.com
CLP-COP: currencylayer.com
CLP-EUR: currencylayer.com
CLP-GBP: currencylayer.com
CLP-JPY: currencylayer.com
CLP-PEN: currencylayer.com
